name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    # Configure AWS Credentials using GitHub Secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    # Change directory to where the Terraform files are located
    - name: Terraform Init
      working-directory: ./network_security_projects/sse_coexistence_testing/terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: ./network_security_projects/sse_coexistence_testing/terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./network_security_projects/sse_coexistence_testing/terraform
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      working-directory: ./network_security_projects/sse_coexistence_testing/terraform
      run: terraform apply -auto-approve